### ISSUE TITLE
How to build MIaS?

### ISSUE THREAD

**Issue by pathakamarnath** [martinliska/WebMIaS#1]
Hello Sir,

Sir I am working on scientific document retrieval. I want to know how to build MIaS.

Please help me.

Thanks!

Amarnath Pathak

**Comment by michal-ruzicka** [comment]
MIaS tools uses [Maven](https://www.google.com/search?q=maven). Open the project in NetBeans, for example, and you are done.

See also https://github.com/martinliska/MIaS/issues/2#issuecomment-230146754.
