### ISSUE TITLE
Want to use TEX to MathML converter

### ISSUE THREAD

**Issue by pathakamarnath** [martinliska/WebMIaS#2]
Sir I want to use TEX to MathML converter in the normal search.java program which comes with Lucene. Can we do that? If yes. please tell me the way to do it.

**Comment by michal-ruzicka** [comment]
Don't now search.java, there are serveral TeX to MathML converters – [LaTeXML](https://www.google.com/search?q=latexml), for example, the integration is up to you. I am not going to write your code for you. ;-)
